In [1]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries imported successfully")

c:\Users\S ATCHAYA SABESAN\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Libraries imported successfully

In [3]:
df = pd.read_csv("cosine_similarity_scores.csv")

print("Number of sentences:", len(df))
print(df.head())

Number of sentences: 10
   Sentence_1_ID  Sentence_2_ID  \
0              1              2
1              3              4
2              5              6
3              7              8
4              9             10

                                          Sentence_1  \
0  Artificial intelligence is transforming many i...
1  Researchers are developing new technologies fo...
2  The government announced new measures to impro...
3  Scientists discovered new evidence about the f...
4  The football team won the championship after a...

                                          Sentence_2  Cosine_Similarity
0  Machine learning allows computers to learn pat...             0.4359
1  Solar power is becoming an important source of...             0.4977
2  Online learning provides students with access ...             0.2384
3  Space telescopes help astronomers study object...             0.4999
4  Athletes require regular training to improve t...             0.0876

In [4]:
model = SentenceTransformer("all-MiniLM-L6-v2")

texts = df["Generated_Text"].astype(str).tolist()

embeddings = model.encode(texts)

print("Embedding shape:", embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2168.70it/s]

KeyError: 'Generated_Text'

In [5]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

texts = sentences

embeddings = model.encode(texts)

print("Embedding shape:", embeddings.shape)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2894.54it/s]

NameError: name 'sentences' is not defined

In [6]:
sentences = [
    "Artificial intelligence is transforming many industries around the world.",
    "Machine learning allows computers to learn patterns from data.",
    "Researchers are developing new technologies for renewable energy.",
    "Solar power is becoming an important source of clean electricity.",
    "The government announced new measures to improve public education.",
    "Online learning provides students with access to educational resources.",
    "Scientists discovered new evidence about the formation of distant galaxies.",
    "Space telescopes help astronomers study objects in the universe.",
    "The football team won the championship after a close final match.",
    "Athletes require regular training to improve their performance.",
    "Climate change is causing significant changes in global weather patterns.",
    "Rising temperatures are affecting ecosystems around the world.",
    "Doctors are using artificial intelligence to assist with medical diagnosis.",
    "Modern hospitals use digital systems to manage patient information.",
    "Electric vehicles are becoming more popular because they produce fewer emissions.",
    "Battery technology is important for the future of electric transportation.",
    "Cybersecurity protects computer systems from unauthorized access.",
    "Strong passwords can help users protect their online accounts.",
    "Social media platforms allow people to communicate and share information.",
    "Digital communication has changed the way people interact with each other."
]

print("Number of sentences:", len(sentences))

Number of sentences: 20

In [7]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

texts = sentences

embeddings = model.encode(texts)

print("Embedding shape:", embeddings.shape)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2872.79it/s]

Embedding shape: (20, 384)

In [8]:
similarity_matrix = cosine_similarity(embeddings)

print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (20, 20)

In [9]:
results = []

for i in range(len(texts)):
    for j in range(i + 1, len(texts)):
        results.append({
            "Text 1": texts[i],
            "Text 2": texts[j],
            "Cosine Similarity": round(similarity_matrix[i][j], 4)
        })

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="Cosine Similarity",
    ascending=False
)

results_df.head(10)

,Text 1,Text 2,Cosine Similarity
145,Climate change is causing significant changes ...,Rising temperatures are affecting ecosystems a...,0.5828
162,Doctors are using artificial intelligence to a...,Modern hospitals use digital systems to manage...,0.5120
99,Scientists discovered new evidence about the f...,Space telescopes help astronomers study object...,0.4999
175,Electric vehicles are becoming more popular be...,Battery technology is important for the future...,0.4997
37,Researchers are developing new technologies fo...,Solar power is becoming an important source of...,0.4977
49,Researchers are developing new technologies fo...,Battery technology is important for the future...,0.4764
184,Cybersecurity protects computer systems from u...,Strong passwords can help users protect their ...,0.4708
11,Artificial intelligence is transforming many i...,Doctors are using artificial intelligence to a...,0.4431
0,Artificial intelligence is transforming many i...,Machine learning allows computers to learn pat...,0.4359
189,Social media platforms allow people to communi...,Digital communication has changed the way peop...,0.4121

In [10]:
top_5 = results_df.head(5)

top_5

,Text 1,Text 2,Cosine Similarity
145,Climate change is causing significant changes ...,Rising temperatures are affecting ecosystems a...,0.5828
162,Doctors are using artificial intelligence to a...,Modern hospitals use digital systems to manage...,0.5120
99,Scientists discovered new evidence about the f...,Space telescopes help astronomers study object...,0.4999
175,Electric vehicles are becoming more popular be...,Battery technology is important for the future...,0.4997
37,Researchers are developing new technologies fo...,Solar power is becoming an important source of...,0.4977

In [11]:
lowest_5 = results_df.tail(5).sort_values(
    by="Cosine Similarity",
    ascending=True
)

lowest_5

,Text 1,Text 2,Cosine Similarity
42,Researchers are developing new technologies fo...,The football team won the championship after a...,-0.1179
125,The football team won the championship after a...,Climate change is causing significant changes ...,-0.1034
130,The football team won the championship after a...,Battery technology is important for the future...,-0.0695
58,Solar power is becoming an important source of...,The football team won the championship after a...,-0.0662
73,The government announced new measures to impro...,The football team won the championship after a...,-0.0604

Observations
Related sentences generally have higher cosine similarity because their meanings are closely connected.
Renewable energy and solar power sentences show high similarity.
Education and online learning sentences also have similar meanings.
Space-related sentences show similarity because they discuss the universe and astronomy.
Unrelated topics generally have lower similarity scores.

In [12]:
np.save("Text_Embedding_Analysis.npy", embeddings)
results_df.to_csv("cosine_similarity_results.csv", index=False)

print("Embeddings saved successfully.")
print("Similarity results saved successfully.")

Embeddings saved successfully.
Similarity results saved successfully.

Importance of Text Embeddings
Text embeddings convert sentences into numerical vectors that represent their meaning. They help computers understand and compare the semantic relationship between different texts.
Applications in LLMs
Semantic Search: Finds relevant information based on meaning instead of exact keywords.
Question Answering: Helps retrieve relevant information to answer user questions.
Recommendation Systems: Finds similar content based on semantic meaning.
Document Similarity: Compares documents and identifies related content.
Chatbots: Helps retrieve relevant context to generate better responses.
Conclusion
This project demonstrates how text embeddings represent sentences as numerical vectors. Cosine similarity is used to measure the semantic similarity between sentence pairs. Higher scores indicate more closely related meanings, while lower scores indicate less related meanings.